### ISSUE TITLE
Plugin outdated

### ISSUE THREAD

**Issue by drak-aquaristik** [pfn/passifox#698]
with the update of keepass 2.42 today this plugin is not any more kompatibel with keepass and is erased from keepass automatically.

**Comment by NorthwoodsTechExploratory** [comment]
Immediately after installing KeePass 2.42, the following error appeared as KeePass loaded.

> The following plugin is incompatible with the current KeePass version:
> C:\Program Files (x86)\KeePass Password Safe 2\KeePassHttp.plgx
> 
> Have a look at the plugin's website for an appropriate version.
> 
> Operation is not valid due to the current state of the object.
> KeePass
>   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
>   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
>   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
>   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
> System.String Compile(System.String, KeePass.Plugins.PlgxPluginInfo, System.String, System.String)

As a result, KeePass is unable to communicate with the browsers Waterfox and Google Chrome. Conditions where the issue is observed follow.

OS:  Windows 7 64-bit
KeePass 2.42
KeePassHttp 1.8.4.2
Waterfox 56.2.9 (64-bit) with KeePassHttp-Connector 1.0.11
Google Chrome 74.0.3729.131 (Official Build) (64-bit) with chromeIPass 2.8.1

Any guidance or information regarding a solution to this issue would be appreciated.

**Comment by libertyx82** [comment]
This is an Problem from KeePassHttp PlugIn and not from chromelPass.

https://github.com/pfn/keepasshttp/issues/384
